### ISSUE TITLE
Escrever Requisitos Não-Funcionais [RNF]

### ISSUE THREAD

**Issue by GianSE** [GianSE/UTF_em_Foco#1]

**Comment by MatheusMeneguim** [comment]
1# 1. Requisitos Não Funcionais

<p align="justify">A <i>Tabela 2</i> a seguir contém os <b>Requisitos Não Funcionais (RNF)</b> elicitados utizando a técnica de Brainstorm .</p>

| ID | Requisito NF | Categoria/Tipo | Prioridade | Requisitos Relacionados |
| :--: | :-----------------------------------------------------------------------: |:-------------: | :--------: | :-----------------: |
| RNF01 | Implementação do sistema em HTML, CSS, JavaScript, PHP. | Produto/Usabilidade | Alta | RNF12 |
| RNF02 | O sistema se comunica com o banco SQL Server | Produto/eficiência | Alta | RNF8 |
| RNF03 | O sistema é executável em qualquer plataforma. | Organizacionais/Implementação | Alta | - |
| RNF04 | O sistema contará com links e informações que serão atualizadas constantemente. | Produto/Usabilidade | Alta | RNF12 |
| RNF05 | A manutenção do sistema só poderá ser feita por usuário permitidos. | Produto/eficiência | Alta | RNF8 |
| RNF06 | Segurança para o usuário através de senhas. | Organizacionais/Implementação | Média | - |
| RNF07 | Fácil de identificar e localizar cada página | Organizacionais/Implementação | Média | - |
| RNF08 | Site responsivo | Organizacionais/Implementação | Alta | - |
| RNF09 | Protocolo HTTPS | Organizacionais/Implementação | Alta | - |
| RNF10 | O site deve ser rápido para voltar caso fique fora do ar | Organizacionais/Implementação | Média | - |
| RNF11 | Site responsivo |  Organizacionais/Implementação | Alta | - | - |
| RNF12 | As consultas ao sistema devem ser respondidas em menos de três segundos | Produto/Eficiência |  Alta | - |


<div style="text-align: center">
<p>Tabela 2: Requisitos Não Funcionais</p>
</div>

# 2. Referências

<a href="../README.md">VOLTAR INÍCIO</a>
