### ISSUE TITLE
Escrever Requisitos Funcionais [RF]

### ISSUE THREAD

**Issue by Emily-UTF** [GianSE/UTF_em_Foco#3]

**Comment by MatheusMeneguim** [comment]
# 1. Requisitos Funcionais

<p align="justify">A <i>Tabela 1</i> a seguir contém os Requisitos Funcionais (RF) elicitados utizando a técnica de Brainstorm.</p>

| ID   |                                 Requisito                                 | Prioridade | Requisitos Relacionados |
| :--: | :-----------------------------------------------------------------------: | :--------: | :---------: |
| RF01 |            O usuário pode criar um cadastro.              |  Média     |    -     |
| RF02 |            O usuário consulta as informações e notícias do site.           |  Alta      |    RF04     |
| RF03 |            O usuário altera informações do cadastro caso necessário .              |  Média     |     RF01      |
| RF04 |            O usuário acessa links para acessar outras páginas.                 |   Alta       |      -       |
| RF05 |            Os administradores inserem notícias no site.        |   Alta         |      -       |
| RF06 |       O usuário consulta uma notícia filtrando por categorias (acadêmico, cultural)    |    Média        |    RF02         |
| RF07 |              O usuário pode excluir um cadastro.           |     Média  |     RF01   |
| RF08 |           O sistema deve garantir a segurança dos dados do usuário, incluindo criptografia da senha.             |    Média   |     -      |
| RF9 |        Os administradores alteram/editam notícias no site.                |    Alta    |     RF05       |
| RF10 |        Os administradores deletam notícias no site.       |      Alta      |      RF05        |
| RF11 | O sistema deve garantir a segurança dos dados do usuário, incluindo criptografia da senha. | Média | - |
| RF12 | O sistema deve permitir que o usuário recupere a senha através de um link enviado para o e-mail cadastrado. | Média | - |
| RF13 | O sistema deve permitir que o usuário faça logout de sua conta de maneira simples, removendo suas credenciais da sessão. | Média | RF14 |
| RF14 | O sistema deve permitir o usuário fazer login, apenas com seu id e senha. | Média | RF13 |
| RF15 | O sistema deve permitir que o usuário faça comentários nas publicações. | Baixa | -|
| RF16 | O sistema deve permitir que o administrador exclua comentários. | Baixa | RF15 |



<div style="text-align: center">
<p>Tabela 1: Requisitos Funcionais</p>
</div>

# 2. Referências


<a href="../README.md">VOLTAR INÍCIO</a>
